### ISSUE TITLE
Multiple definition errors when including sf_external.h

### ISSUE THREAD

**Issue by jamespeapen** [traversc/stringfish#23]
Thanks for this package! I've been using it to write my own and its been working great until recently when including `sf_external.h` in a header file that's also included by another file.

There are 4 files involved in [my package](https://github.com/huishenlab/iscream/tree/sf):
- [`query_all.hpp`](https://github.com/huishenlab/iscream/blob/sf/src/query_all.hpp) includes [`query.hpp`](https://github.com/huishenlab/iscream/blob/sf/src/query.hpp) and previously included `sf_external.h`
- [`RcppFunctions.cpp`](https://github.com/huishenlab/iscream/blob/sf/src/RcppFunctions.cpp) includes [`query_all.hpp`](https://github.com/huishenlab/iscream/blob/sf/src/query_all.hpp)

With `sf_external.h` &rarr; `query_all.hpp`  &rarr; `RcppFunctions.cpp`, there are no errors.

I moved the `sf_external.h` include directive from `query_all.hpp` to [`query.hpp`](https://github.com/huishenlab/iscream/blob/sf/src/query.hpp) so that I can use stringfish in `query.cpp`.

Now with `sf_external.h` &rarr; `query.hpp`  &rarr; `query_all.hpp`  &rarr; `RcppFunctions.cpp`, compiling produces multiple definition errors for every function in `sf_external.h`.

However, compilation works when I copy the `sf_external.h` and `sf_internal.h` files to my repo, modify all functions in `sf_external` and `get_rstring_type_internal` in `sf_internal` to be static.

I'm not sure where I'm going wrong since `sf_external.h` is used in the qs package without any issues in a similar way with indirect imports.

**Comment by traversc** [comment]
Hi James, glad you are finding use out of this!

The One Definition Rule states that you cant have the same function definition in the entire _program_, so since you are including `query.hpp` in more than one cpp file it makes sense that you get that error. Using the static keyword restricts function scope to the translation unit, so fixes the issue. 

`sf_external.h` should be changed to static or better, inline. 

In the `qs` package Im following the [Single Compilation Unit approach](https://en.wikipedia.org/wiki/Single_compilation_unit) to avoid these issues. I recommend this approach but it might raise some eyebrows.

**Comment by jamespeapen** [comment]
I'll try that - thanks!
