### ISSUE TITLE
Default option for the nthreads

### ISSUE THREAD

**Issue by artemklevtsov** [traversc/stringfish#5]
Something like this:

```r
sf_iconv(x, from, to, nthreads = getOptions("stringfish.nthreads", 1L))
```

**Comment by traversc** [comment]
I'm reluctant to use this approach because of using too many threads with R parallelization (mclapply etc). 

E.g. you might set this option at the top of your script but then forget to reset it in a parallel loop. 

I know it's possible to reset an option after forking, but it adds unnecessary complexity.
